Update YML

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,15 +30,13 @@ jobs:
 
       - name: Ensure App Service exists
         run: |
-          if ! az webapp show \
-            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
-            --resource-group ${{ secrets.AZURE_RG }}; then
-              echo "Web App not found. Creating it..."
-              az webapp create \
-                --name ${{ secrets.AZURE_WEBAPP_NAME }} \
-                --resource-group ${{ secrets.AZURE_RG }} \
-                --plan ${{ secrets.AZURE_APP_PLAN }} \
-                --runtime "PYTHON|3.10"
+          if ! az webapp show --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RG }}; then
+            echo "Web App not found. Creating it..."
+            az webapp create \
+              --name ${{ secrets.AZURE_WEBAPP_NAME }} \
+              --resource-group ${{ secrets.AZURE_RG }} \
+              --plan ${{ secrets.AZURE_APP_PLAN }} \
+              --runtime "PYTHON|3.10"
           fi
 
       - name: Zip project
